# Generated by Django 3.2.9 on 2021-12-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('profit', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('inst_cv', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
