# Generated by Django 3.2.9 on 2021-12-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate_Customer',
            fields=[
                ('corp_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
                ('due_fee', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Retail_Customer',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
                ('due_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('profit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('regular_price', models.IntegerField()),
                ('cat_id', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.category')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=30)),
                ('regular_fee', models.IntegerField()),
                ('discount_fee', models.IntegerField()),
                ('ad_closed', models.BooleanField()),
                ('corp_id', models.ForeignKey(blank=True, db_column='corp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.corporate_customer')),
                ('cust_id', models.ForeignKey(blank=True, db_column='cust_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.retail_customer')),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.instructor')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.user')),
            ],
        ),
    ]
