# Generated by Django 3.2.9 on 2021-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereport',
            name='check_ref_no1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='check_ref_no2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='check_ref_no3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salereport',
            name='check_ref_no4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
