# Generated by Django 3.2.9 on 2021-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_designation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_id',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_phone',
            field=models.CharField(blank=True, max_length=22, unique=True),
        ),
    ]
