# Generated by Django 3.2.9 on 2021-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0002_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retail_Customer',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
                ('due_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('profit', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('user_cv', models.FileField(upload_to='')),
            ],
        ),
    ]
