# Generated by Django 3.2.9 on 2021-12-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0002_auto_20211208_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pay_method',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
