# Generated by Django 3.2.9 on 2021-12-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0002_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
