# Generated by Django 3.2.9 on 2021-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0002_auto_20211223_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='prev_receipts',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
