# Generated by Django 3.2.9 on 2021-12-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0003_auto_20211207_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='address',
            new_name='inst_address',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='designation',
            new_name='inst_designation',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='email',
            new_name='inst_email',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='inst_name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='organization',
            new_name='inst_organization',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='phone',
            new_name='inst_phone',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='profit',
            new_name='inst_profit',
        ),
    ]
