# Generated by Django 3.2.9 on 2021-12-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0003_retail_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate_Customer',
            fields=[
                ('corp_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('total_fee', models.IntegerField()),
                ('paid_fee', models.IntegerField()),
                ('due_fee', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('regular_price', models.IntegerField()),
                ('outline', models.FileField(upload_to='')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_backend.category')),
            ],
        ),
    ]
