# Generated by Django 3.2.9 on 2022-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0004_instructorfeereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorfeereport',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
