# Generated by Django 3.2.9 on 2021-12-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0004_auto_20211207_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='designation',
            new_name='user_designation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profit',
            new_name='user_profit',
        ),
    ]
