# Generated by Django 3.2.9 on 2021-12-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0004_remove_sale_pay_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyReceipt',
            fields=[
                ('receipt_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('receipt', models.FileField(upload_to='')),
                ('pay_method', models.CharField(max_length=100)),
                ('check_ref_no', models.CharField(max_length=80)),
                ('corp_id', models.ForeignKey(blank=True, db_column='corp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.corporate_customer')),
                ('cust_id', models.ForeignKey(blank=True, db_column='cust_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.retail_customer')),
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.sale')),
            ],
        ),
    ]
