# Generated by Django 3.2.9 on 2021-12-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0004_corporate_customer_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_backend.category', verbose_name='cat_id'),
        ),
    ]
