# Generated by Django 3.2.9 on 2022-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_backend", "0005_instructorfeereport_check_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_id",
            field=models.CharField(max_length=255, primary_key=True, unique=True),
        ),
    ]
