# Generated by Django 3.2.9 on 2021-12-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0005_alter_course_cat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cat_id',
            field=models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.category'),
        ),
    ]
