# Generated by Django 3.2.9 on 2021-12-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0005_auto_20211207_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='address',
            new_name='corp_address',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='due_fee',
            new_name='corp_due_fee',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='email',
            new_name='corp_email',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='name',
            new_name='corp_name',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='paid_fee',
            new_name='corp_paid_fee',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='phone',
            new_name='corp_phone',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='total_fee',
            new_name='corp_total_fee',
        ),
        migrations.RenameField(
            model_name='corporate_customer',
            old_name='units',
            new_name='corp_units',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='address',
            new_name='cust_address',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='designation',
            new_name='cust_designation',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='due_fee',
            new_name='cust_due_fee',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='email',
            new_name='cust_email',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='name',
            new_name='cust_name',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='organization',
            new_name='cust_organization',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='paid_fee',
            new_name='cust_paid_fee',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='phone',
            new_name='cust_phone',
        ),
        migrations.RenameField(
            model_name='retail_customer',
            old_name='total_fee',
            new_name='cust_total_fee',
        ),
    ]
