# Generated by Django 3.2.9 on 2022-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training_backend", "0006_alter_batch_batch_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="batch_num",
            field=models.IntegerField(default=2101, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_id",
            field=models.BigAutoField(primary_key=True, unique=True),
        ),
    ]
