# Generated by Django 3.2.9 on 2022-01-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0007_auto_20220125_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_num',
            field=models.IntegerField(),
        ),
    ]
