# Generated by Django 3.2.9 on 2021-12-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0007_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='inst_cv',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_cv',
        ),
    ]
