# Generated by Django 3.2.9 on 2021-12-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0007_alter_retail_customer_cust_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_due_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_paid_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='retail_customer',
            name='cust_total_fee',
            field=models.IntegerField(blank=True),
        ),
    ]
