# Generated by Django 3.2.9 on 2021-12-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0008_auto_20211207_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='Sale',
        ),
    ]
