# Generated by Django 3.2.9 on 2022-01-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0009_instructorfeereport_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereport',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default='DEV0001', on_delete=django.db.models.deletion.CASCADE, to='training_backend.course'),
            preserve_default=False,
        ),
    ]
