# Generated by Django 3.2.9 on 2021-12-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0009_rename_batch_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='discount_fee',
            new_name='sale_fee',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='ad_closed',
        ),
    ]
