# Generated by Django 3.2.9 on 2021-12-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0009_alter_batch_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='outline',
        ),
    ]
