# Generated by Django 3.2.9 on 2021-12-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0011_rename_batch_sale_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('batch_fee', models.IntegerField()),
                ('admit_closed', models.BooleanField()),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.course')),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.instructor')),
            ],
        ),
    ]
