# Generated by Django 3.2.9 on 2021-12-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0012_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='batch_id',
            new_name='batch',
        ),
    ]
