# Generated by Django 3.2.9 on 2021-12-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0012_auto_20211206_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='corp_id',
            field=models.ForeignKey(blank=True, db_column='corp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.corporate_customer'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='cust_id',
            field=models.ForeignKey(blank=True, db_column='cust_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.retail_customer'),
        ),
    ]
