# Generated by Django 3.2.9 on 2021-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0013_auto_20211206_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
