# Generated by Django 3.2.9 on 2021-12-07 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0013_rename_batch_id_sale_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='batch',
        ),
        migrations.AddField(
            model_name='sale',
            name='batch_id',
            field=models.ForeignKey(db_column='batch_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='training_backend.batch'),
            preserve_default=False,
        ),
    ]
