# Generated by Django 3.2.9 on 2021-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0014_alter_batch_batch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_id',
            field=models.CharField(max_length=30),
        ),
    ]
