# Generated by Django 3.2.9 on 2021-12-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0015_auto_20211206_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
