# Generated by Django 3.2.9 on 2021-12-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_backend', '0016_delete_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=30)),
                ('regular_fee', models.IntegerField()),
                ('discount_fee', models.IntegerField()),
                ('ad_closed', models.BooleanField()),
                ('corp_id', models.ForeignKey(blank=True, db_column='corp_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.corporate_customer')),
                ('cust_id', models.ForeignKey(blank=True, db_column='cust_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='training_backend.retail_customer')),
                ('inst_id', models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.instructor')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='training_backend.user')),
            ],
        ),
    ]
