from django.conf.urls import url
from training_backend import views

urlpatterns = [
    url(r"^backend/api/instructors$", views.instructor_list),
    url(r"^backend/api/instructors/(?P<pk>[a-zA-Z0-9_]+)$", views.instructor_detail),
    url(r"^backend/api/instructors-count$", views.instructor_count),
    url(
        r"^backend/api/instructor-percentage/([a-zA-Z0-9_]+)$",
        views.instructor_percentage,
    ),
    url(r"^backend/api/instructor-total/([a-zA-Z0-9_]+)$", views.instructor_total),
    url(r"^backend/api/instructor-fee-update$", views.instructor_fee_update),
    url(r"^backend/api/users$", views.user_list),
    url(r"^backend/api/users/(?P<pk>[a-zA-Z0-9_]+)$", views.user_detail),
    url(r"^backend/api/users-count$", views.user_count),
    url(r"^backend/api/user-percentage/([a-zA-Z0-9_]+)$", views.user_percentage),
    url(r"^backend/api/categories$", views.category_list),
    url(r"^backend/api/categories/(?P<pk>[a-zA-Z0-9_]+)$", views.category_detail),
    url(r"^backend/api/categories-count$", views.category_count),
    url(r"^backend/api/courses$", views.course_list),
    url(r"^backend/api/courses/(?P<pk>[a-zA-Z0-9_]+)$", views.course_detail),
    url(r"^backend/api/courses-count$", views.course_count),
    url(r"^backend/api/batches$", views.batch_list),
    url(r"^backend/api/batches-by-course$", views.batch_by_course),
    url(r"^backend/api/batch-list$", views.batch_list_table),
    url(r"^backend/api/batches/(?P<pk>[a-zA-Z0-9_]+)$", views.batch_detail),
    url(r"^backend/api/batch-ids$", views.batch_ids),
    url(r"^backend/api/batch-admission/(?P<pk>[a-zA-Z0-9_]+)$", views.batch_admission),
    url(r"^backend/api/batches-count$", views.batch_count),
    url(r"^backend/api/customers$", views.customer_list),
    url(
        r"^backend/api/customers/(?P<pk>[a-zA-Z0-9_]+)$",
        views.customer_detail,
    ),
    url(r"^backend/api/customer-fee-update$", views.customer_fee_update),
    url(r"^backend/api/customers-count$", views.customer_count),
    # url(r"^backend/api/corporate-customers$", views.corporate_customer_list),
    # url(
    #     r"^backend/api/corporate-customers/(?P<pk>[a-zA-Z0-9_]+)$",
    #     views.corporate_customer_detail,
    # ),
    # url(r"^backend/api/corporate-customers-count$", views.corporate_customer_count),
    # url(r"^backend/api/corporate-fee-update$", views.corporate_fee_update),
    url(r"^backend/api/sales$", views.sale_report),
    # url(r"^backend/api/sales/(?P<pk>[a-zA-Z0-9_]+)$", views.sale_detail),
    # url(r"^backend/api/sales-count$", views.sale_count),
    url(r"^backend/api/sale-id$", views.sale_id),
    url(r"^backend/api/sale-update$", views.sale_update),
    url(r"^backend/api/sale-list$", views.sale_list),
    url(
        r"^backend/api/sale-customer-list/([a-zA-Z0-9_]+)$",
        views.sale_report_with_customers,
    ),
]
